name: CI Preview Dev Center

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch: {}

jobs:
  preview-build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger CircleCI Preview Build
      run: |
        curl --location 'https://circleci.com/api/v2/project/gh/bigcommerce/developer-center/pipeline' \
        --header 'Circle-Token: ${{ secrets.CIRCLECI_TOKEN }}' \
        --header 'content-type: application/json' \
        --data "{
            \"branch\": \"${{ github.ref_name }}\",
            \"parameters\": {
                \"build_environment\": \"preview\",
                \"github_triggering_actor\": \"${{ github.actor }}\"
            }
        }"
